### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by GabrielLin** [Pelhans/Neural_dependency_parsing#1]
> Epoch 1 out of 25
> 22/22 [============================>.] - ETA: 0s - train loss: 0.4864Evaluating on dev set
>  Traceback (most recent call last):
>   File "parser_model.py", line 516, in <module>
>     main(Flags.TRAIN, load_existing_dump=True)
>   File "parser_model.py", line 460, in main
>     model.fit(sess, saver, config, dataset, train_writer, valid_writer, merged)
>   File "parser_model.py", line 380, in fit
>     valid_UAS, valid_LAS = self.run_valid_epoch(sess, dataset)
>   File "parser_model.py", line 365, in run_valid_epoch
>     self.compute_dependencies(sess, dataset.valid_data, dataset)
>   File "parser_model.py", line 295, in compute_dependencies
>     zip(curr_sentences, self.legal_transitions)]
>   File "/data1/myname/nlp/Neural_dependency_parsing/bin/../utils/feature_extraction.py", line 272, in update_state_by_transition
>     self.stack.append(self.buff[0])
> IndexError: list index out of range
> 

When I ran parser_model.py, it shew above error. Could you please give me some suggestions? Thanks.

**Comment by Pelhans** [comment]
Sorry for lately reply. Have you changed source code, I check it but found class Dataset(object): in line 272 ....
self.stack.append(self.buff[0]) means when  we apply shift, we append the first word in buffer to stack. So this error should be caused when no words left in buffer but you still get word. Maybe you can check it from legal_labels function

**Comment by GabrielLin** [comment]
Sorry, I have confirmed that it is the issue of my reformation.
